### ISSUE TITLE
위키피디아 데이터를 활용하여 KenLM(4-gram) 모델 구축 방법 질문

### ISSUE THREAD

**Issue by JoungheeKim** [qute012/quartznet-ko#1]
안녕하세요? 
좋은 모듈을 공개해 주셔서 감사합니다.

몇가지 궁금한게 있어서 이슈를 남기게 되었습니다.

AIHUB 음성인식 성능을 향상시키기 위하여 위키피디아 데이터를 활용하여 KenLM(4-gram) 모델을 구축하고 Decoding 과정에 활용하였다고 Read.me 파일에 기술해주셨는데

1. 위키피디아 데이터를 공유 받을 수 있을까요?
    (출처와 스크래핑 방식, 데이터 다운로드 경로 등) 이 궁금합니다.

2. 개발해 주신 것과 관련된 문서(논문, 튜토리얼)이 존재하나요??
    갖고 계시다면 공유가 가능한지 여쭙고 싶습니다.

감사합니다.

**Comment by dobby-seo** [comment]
1. 데이터는 코위키(https://dumps.wikimedia.org/kowiki/)에서 덤프 파일로 다운로드 받았습니다.
실행 방법은 KenLM document와 https://github.com/mozilla/DeepSpeech/issues/1236 를 참고하시면 좋을 듯 합니다.

2. 원 논문과 DeepSpeech를 참고하시면 좋을 듯 합니다.
QuartzNet: https://arxiv.org/abs/1910.10261
DeepSpeech2: https://arxiv.org/abs/1512.02595

관심 가져주셔서 감사합니다. 현재는 대부분 음성 모델링이 Transformer(Conformer) 기반으로 넘어왔으니 참고하시면 좋을 듯 합니다 :D



> 안녕하세요?
> 좋은 모듈을 공개해 주셔서 감사합니다.
> 
> 몇가지 궁금한게 있어서 이슈를 남기게 되었습니다.
> 
> AIHUB 음성인식 성능을 향상시키기 위하여 위키피디아 데이터를 활용하여 KenLM(4-gram) 모델을 구축하고 Decoding 과정에 활용하였다고 Read.me 파일에 기술해주셨는데
> 
> 1. 위키피디아 데이터를 공유 받을 수 있을까요?
>    (출처와 스크래핑 방식, 데이터 다운로드 경로 등) 이 궁금합니다.
> 2. 개발해 주신 것과 관련된 문서(논문, 튜토리얼)이 존재하나요??
>    갖고 계시다면 공유가 가능한지 여쭙고 싶습니다.
> 
> 감사합니다.

**Comment by JoungheeKim** [comment]
답변과 자료공유 감사합니다.
계속 귀찮게 해서 정말 죄송하지만 데이터와 관련해서 좀 더 궁금한게 있어서 이슈를 남깁니다.

사용하신 데이터 중에서 Aihub데이터 즉 한국어음성 데이터의 전처리와 관련된 질문을 드립니다.

1. Aihub 음성 데이터의 스크립트를 보면 아래와 같은 형태로 제공되고 있습니다.
```python
	b/ (70%)/(칠 십 퍼센트) 확률이라니 아/ (뭐+ 뭔)/(모+ 몬) 소리야 진짜 (100%)(백 프로)가 왜 안돼? n/
```

이중에서 혹시 어떻게 전처리해서 사용했는지 궁금합니다.
발음을 기준으로 전처리 했는지
```python
     칠 십 퍼센트 확률이라니 아 모 몬 소리야 진짜 백 프로가 왜 안돼?
```
스크립트를 기준으로 전처리 했는지
```python
     70% 확률이라니 아 뭐 뭔 소리야 진짜 100%가 왜 안돼?
```


2. 대화 스크립트 개발 단위(음소, 단어, character)가 궁금합니다.
코드에는 id2char로만 되어 있어서 확연히 구별이 가지 않습니다.

음소 단위라면
```python
 ㅊㅣㄹ  ㅅㅣㅂ ㅍㅓㅅㄴㅌㅡ ㅎㅗㅏㄱㄹㅠㄹㅇㅣㄹㅏㄴㅣ
```
character 단위라면
```python
칠 십   퍼 센 트   확 률 이 라 니
```

위와 같이 선택하여 개발이 가능하다는 것을 들었습니다.
개발자님께서는 어떤걸 선택하셨는지 궁금합니다.

마지막으로 전체 스크립트가 아니더라도 vocab을 구축하신걸 갖고 계신다면 공유를 요청드려도 될까요?
코드 분석에 활용하고 싶습니다.

답변 주셔서 감사합니다.

**Comment by dobby-seo** [comment]
여러가지 실험을 해봤을 때, 한국어는 캐릭터(그래핌) 레벨에서 인식률이 좋은 것 같네요.
발음을 기준으로 전 처리하였고, 사실 해당 프로젝트는 개인 테스트용으로 올린거라 사용해보실지는 몰랐네요ㅎㅎ...

혹시 연구 실험을 위해서 진행하시는 거라면, 제가 배포한 트랜스포머 기반 음성인식기에서 아래 링크를 사용하시는걸 추천 드립니다.
https://github.com/qute012/kosr/tree/main/kosr/data/Ksponspeech

baseline 실험이 공개되었고, ESPNet에 egs로 KsponSpeech로 전사 파일과 학습파일이 공개되어있습니다. 위에 파일은 전처리를 거친 데이터를 올려놓았고 원 논문(https://www.mdpi.com/2076-3417/10/19/6936)과 동일한 실험 조건입니다. Vocab도 존재하니 가져다 쓰시면 될 것 같네요.

외에도 Kospeech(https://github.com/sooftware/KoSpeech) 프로젝트에 많은 음성인식 모델들이 있어서 사용해보시길 추천드립니다.

**Comment by JoungheeKim** [comment]
성실하게 답변주셔서 너무 감사합니다.
