### ISSUE TITLE
Pre-trained model 제공 관련

### ISSUE THREAD

**Issue by jung-youjin** [qute012/quartznet-ko#2]
안녕하세요! 좋은 프로젝트 감사합니다.

해당 분야에 관심이 많은데 처음 시작한 학생이어서 마땅한 training시킬 수 있는 하드웨어 환경이 없는 상황입니다. 혹시 해당 프로젝트로 만들어진 pre-trained model 제공이 가능한지 여쭙고 싶습니다. 

감사합니다!

**Comment by dobby-seo** [comment]
@jung-youjin 

프로젝트에 관심가져주셔서 감사합니다. 아쉽지만 현재 작업 했던 서버에 접근할 수 없고, 백업한 파일이 없어서 제공해드리지는 못 하네요.
혹시 공부를 위해서 모델 training step을 밟고 계신거라면 colab 사용을 추천드리구요. 경량화된 모델이여서 학습속도는 비교적 빠르다고 생각이 됩니다. 혹시 현재 필요로 하신 부분이 음성인식 모델이라면, 상용화된 API 또는 [Pororo] 프로젝트에서 사용이 가능한걸로 알고있습니다.

[Pororo]: https://github.com/kakaobrain/pororo

**Comment by jung-youjin** [comment]
@qute012 

안녕하세요! colab으로 train이 가능하다니 큰 희소식이네요... 여러 오픈소스를 찾아보다가 음성/자연어 처리는 colab으로 train이 어렵다는 문의 답변을 여러차례 받았던 차여서 걱정이 많았습니다...! 이렇게 좋은 모델 공유해주셔서 정말 감사합니다ㅜㅜ 현재 train에 대한 공부와 더불어, 오프라인 환경 임베디드 보드에 한국어 음성인식 모델을 직접 프로젝트에 적용해보고자 하는 단계에 있습니다. zeroth, KoSpeech 등에 대해서만 알고 Pororo에 대해서는 무지했는데 좋은 방향성 제시해주셔서 정말 감사합니다!

많은 도움 되었습니다! 🙏🏼
